name: Docker

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

env:
  IMAGE_NAME: portfolio

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build . --file .docker/Dockerfile -t ${{ secrets.PORTFOLIO_REPOSITORY }}
          docker tag ${{ secrets.PORTFOLIO_REPOSITORY }}:latest ${{ secrets.REPOSITORY_URL }}

      - name: Installing CLI
        run: |
          pip install awscli
      - name: Push Docker Image
        run: |
          echo ${{ secrets.AWS_DEFAULT_REGION }}
          echo ${{ secrets.AWS_ECR_PORTFOLIO_PATH }}
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_PORTFOLIO_PATH }}
          docker push ${{ secrets.REPOSITORY_URL }}


  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Deploy image
        run: |
          echo "Reached to deply"
